
# export N_PREFIX=~/.npm
# export PATH="$N_PREFIX/bin:$PATH"

# zmodload zsh/zprof
export NPM_TOKEN=${NPM_TOKEN:-""}

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/ndk/23.0.7599858
export NDK_PROJECT_PATH=$ANDROID_HOME/ndk/23.0.7599858
export PATH=$PATH:/Users/chriscolborne/google-cloud-sdk/platform/google_appengine

export PATH=/usr/local/bin:$PATH:/opt/ss-arcanist/arcanist/bin:~/Code/go/bin:~/.composer/vendor/bin/
export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

autoload -U bashcompinit
bashcompinit
eval "$(register-python-argcomplete pipx)"

timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}


export PYLINTRC=/Users/chriscolborne/Code/clipchamp-stack/.pylintrc
export MODIFY_PYFILES_IN_HOOK=1

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git docker docker-compose npm brew osx vi-mode node)
export NVM_LAZY_LOAD=false
export NVM_COMPLETION=true
export NVM_AUTO_USE=true
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('git', 'npx', 'make')
plugins=(zsh-nvm vi-mode)

source $ZSH/oh-my-zsh.sh
source /opt/homebrew/etc/profile.d/z.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs vi_mode time)

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Prevent less from capturing screen
export LESS="-Xr"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias ghc="gh copilot"
alias hibernateon="sudo pmset -a hibernatemode 25"
alias hibernateoff="sudo pmset -a hibernatemode 3"
alias ll="ls -alFG"
alias grep='grep --color=always'
alias grepnc='grep --color=never'
alias psaux='ps axo user:20,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm,args'
alias rg='rg -S'
alias dc='docker-compose'
alias dcw='docker-compose exec web'
alias dcm='docker-compose exec mysql'
alias ac="dcw bin/console"
alias lcc='fc -ln -1 | awk "{\$1=\$1}1" ORS="" | pbcopy'
alias phpstan='docker run -v $PWD:/app --rm phpstan/phpstan'
alias hg=gh
alias cc='make --directory=/Users/chriscolborne/Code/clipchamp-stack --no-print-directory --'
alias gmm='git co master && git pull && git co - && git merge master'
alias grm='git co master && git pull && git co - && git rebase master'
alias azl='az repos pr list -o table'
alias azco='az repos pr checkout --id'
alias azo='az repos pr show --open --id'
alias azp='az repos pr create --draft --open'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# fish style auto suggest
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"

# export WORKON_HOME=~/.virtualenvs/
# source /usr/local/bin/virtualenvwrapper.sh
# workon cc_stack
# workon venv39
# . /Users/chriscolborne/Code/clipchamp-stack/.venv39/bin/activate

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/usr/local/opt/curl/bin:$PATH"

export NODE_OPTIONS="--max-old-space-size=16384"

#source /usr/local/opt/asdf/libexec/asdf.sh

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# # place this after nvm initialization!
# autoload -U add-zsh-hook
# load-nvmrc() {
#   local node_version="$(nvm version)"
#   local nvmrc_path="$(nvm_find_nvmrc)"

#   if [ -n "$nvmrc_path" ]; then
#     local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

#     if [ "$nvmrc_node_version" = "N/A" ]; then
#       nvm install
#     elif [ "$nvmrc_node_version" != "$node_version" ]; then
#       nvm use
#     fi
#   elif [ "$node_version" != "$(nvm version default)" ]; then
#     echo "Reverting to nvm default version"
#     nvm use default
#   fi
# }
# add-zsh-hook chpwd load-nvmrc
# load-nvmrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/chriscolborne/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/chriscolborne/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/chriscolborne/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/chriscolborne/google-cloud-sdk/completion.zsh.inc'; fi

source ~/.torusrc

export PATH="${PATH}:/Users/chriscolborne/.azureauth/0.8.4"

export PATH="${PATH}:/Users/chriscolborne/.azureauth/0.8.3"


# Created by `pipx` on 2025-05-19 01:55:04
export PATH="$PATH:/Users/chriscolborne/.local/bin"
