# turn off Ctrl + s XOFF (XON is Ctrl + q)
tty -s && stty ixany
tty -s && stty ixoff -ixon
tty -s && stty stop undef
tty -s && stty start undef

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
