# turn off Ctrl + s XOFF (XON is Ctrl + q)
tty -s && stty ixany
tty -s && stty ixoff -ixon
tty -s && stty stop undef
tty -s && stty start undef

alias ll="ls -alrtF --color"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export PATH=$PATH:/Applications/acquia-drupal/drush

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

export NVM_DIR="/Users/zorfling/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
